### ISSUE TITLE
Test that 3 previous, current, and next versions of Firefox get sent to /[locale]/firefox/fx

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#212]
We need a test for the following:

1. Given any of the following Firefox versions: past 3 versions, current version, next three versions (.e.g.: Beta, Aurora, Nightly)
2. When a user hits www.mozilla.org or www.mozilla.com, they should go to /[locale]/firefox/fx
3. All other users should get /[locale]/firefox/new/

This is from https://bugzilla.mozilla.org/show_bug.cgi?id=892716

**Comment by davehunt** [comment]
@jgmize @pmclanahan is this scenario now covered by the bedrock redirect tests? if not, is it still a valid scenario to test?

**Comment by pmclanahan** [comment]
I don't think we have this covered anywhere at present. Not sure if this is even still the plan.

**Comment by davehunt** [comment]
The tests have been migrated to the https://github.com/mozilla/bedrock repository. If this is still needed, it should be opened there.
