### ISSUE TITLE
Need a redirect test for additional /firstrun logic/acceptance of beta/b in Firefox versions

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#261]
This is high priority -- we need a test for the following (we should be as thorough as we can):

"404: http://www.mozilla.org/en-US/firefox/27.0beta/firstrun/

200k: http://www.mozilla.org/en-US/firefox/27.0b/firstrun/

It seems that the firstrun urls are assuming [0-9]+\.[0-9]+(a|b)*[0-9]*

/[version].[sub version](optional a or b)[optional number]/firstrun/

We should change the logic to allow for b or beta, i.e. b[a-z]* or (b|beta)"

https://bugzilla.mozilla.org/show_bug.cgi?id=953131#c10

**Comment by davehunt** [comment]
No response for over a year so I'm going to close this issue. Let's open a new issue if we still need new tests or enhancements.
