### ISSUE TITLE
Figure out what to do with test_links_on_firefox_all and test_links_on_firefox_organization

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#347]
We need to figure out what to do with tests like:

test_links_on_firefox_all[1] and test_links_on_firefox_organization_all[2]

The problem is (for whatever reason -- and we should dig into this regardless) our entire suite will fail, at times, due to connection/retry-timeouts like:

E ConnectionError: HTTPSConnectionPool(host='download-installer.cdn.mozilla.net', port=443): Max retries exceeded with url: /pub/firefox/releases/33.0/linux-x86_64/lt/firefox-33.0.tar.bz2 (Caused by <class 'socket.error'>: [Errno 60] Operation timed out)

[1] https://github.com/mozilla/mcom-tests/blob/master/tests/test_l10n_download_links.py#L58
[2] https://github.com/mozilla/mcom-tests/blob/master/tests/test_l10n_download_links.py#L66

@jgmize @pmclanahan @chrismore - I'm actually already going to email RelEng / Webtools et al. about https://github.com/mozilla/bouncer-tests - is the coverage we have here helpful?  It doesn't seem actionable, at least not by this team (#www), and while it might give IT/Web Ops some more info, I feel it's time to think about a better place for it.  cc @superawesome

**Comment by davehunt** [comment]
Closing this - we're currently working on having a regular link checker crawl the site and report all broken links. This will result in an actionable list, but does not need to block a release.
