### ISSUE TITLE
Investigate/fix test_tabzilla_links_are_visible

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#378]
py.test -r fsxXR -reruns=5 -v -n 4 --api=webdriver --browsername=Firefox --browserver=33 --platform=mac --baseurl=https://www.mozilla.org --credentials=/Users/webqa/webqa-credentials/mcom.yaml --junitxml=results.xml

14:54:52 =================================== FAILURES ===================================
14:54:52 ________________ TestAboutPage.test_tabzilla_links_are_visible _________________
14:54:52 [gw0] darwin -- Python 2.7.5 /Users/Shared/Jenkins/Home/jobs/mozilla.org.prod/workspace/.env/bin/python
14:54:52 self = <tests.test_about.TestAboutPage instance at 0x10644b248>
14:54:52 mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x107695758>
14:54:52 
14:54:52     @pytest.mark.nondestructive
14:54:52     def test_tabzilla_links_are_visible(self, mozwebqa):
14:54:52         about_page = AboutPage(mozwebqa)
14:54:52         about_page.go_to_page()
14:54:52         Assert.true(about_page.header.is_tabzilla_panel_visible)
14:54:52         about_page.header.toggle_tabzilla_dropdown()
14:54:52         bad_links = []
14:54:52         for link in about_page.header.tabzilla_links_list:
14:54:52             if not about_page.is_element_visible(*link.get('locator')):
14:54:52                 bad_links.append('The link at %s is not visible' % link.get('locator')[1:])
14:54:52 >       Assert.equal(0, len(bad_links), '%s bad links found: ' % len(bad_links) + ', '.join(bad_links))
14:54:52 
14:54:52 tests/test_about.py:75: 
14:54:52 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
14:54:52 
14:54:52 self = <class 'unittestzero.Assert'>, first = 0, second = 1
14:54:52 msg = '1 bad links found: The link at #tabzilla-nav > ul > li:nth-child(1) > div > ul > li:nth-of-type(1) > a is not visible'
14:54:52 
14:54:52     @classmethod
14:54:52     def equal(self, first, second, msg=None):
14:54:52         """
14:54:52             Asserts that 2 elements are the same
14:54:52     
14:54:52             :Args:
14:54:52              - First object to be tested
14:54:52              - Second object to be tested
14:54:52              - Message that will be printed if it fails
14:54:52             """
14:54:52 >       assert first == second, msg
14:54:52 E       AssertionError: 1 bad links found: The link at #tabzilla-nav > ul > li:nth-child(1) > div > ul > li:nth-of-type(1) > a is not visible
14:54:52 
14:54:52 .env/lib/python2.7/site-packages/unittestzero.py:55: AssertionError
14:54:52 ------------------------------- pytest-mozwebqa --------------------------------
14:54:52 Failing URL: https://www.mozilla.org/en-US/about/

**Comment by justinpotts** [comment]
@stephendonner This is passing now on Jenkins, correct?

**Comment by stephendonner** [comment]
Yes; closing -- thanks for the ping!
