### ISSUE TITLE
Remove 3 failing and problematic email/form-submission tests

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#386]
We ( @jgmize @pmclanahan me ) discussed this in IRC and have agreed to remove 3 email-signup tests that we haven't run for a long time, are failing, and even when passing cause problems with Basket; we recently reintroduced this into the runs with --destructive on the jobs' commandline.

TestAboutPage.test_sign_up_form_submit_is_successful
TestHomePage.test_sign_up_form_submit_is_successful
TestContribute.test_sign_up_with_valid_email

Thx to @kyoshino for graciously agreeing to being cajoled into taking this :+1:

**Comment by kyoshino** [comment]
Yes I'm looking into this.
