### ISSUE TITLE
Add regression test to ensure both stub and full-download installers are linked on Download page

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#396]
Per https://github.com/mozilla/bedrock/pull/2880#issuecomment-88195918 and https://bugzilla.mozilla.org/show_bug.cgi?id=1149620, let's see if we can add a regression test for the Download page, to ensure both stub and full-download installers are linked.

**Comment by kyoshino** [comment]
Thanks, I'll take a look later.

**Comment by rbillings** [comment]
@kyoshino are you still working on this?

**Comment by kyoshino** [comment]
Sorry, forgot about it. Will work sometime this week.

**Comment by davehunt** [comment]
Do we still need this? How do we check if a link is to the stub installer rather than the full installer?

**Comment by davehunt** [comment]
The tests have been migrated to the https://github.com/mozilla/bedrock repository. If this is still needed, it should be opened there.
