### ISSUE TITLE
Fix flake8 failures

### ISSUE THREAD

**Issue by davehunt** [mozilla/mcom-tests#401]
There are currently a number of flake8 failures as indicated by the [Travis-CI builds](https://travis-ci.org/mozilla/mcom-tests). Let's clean these up!

You will need to install flake8:
```
pip install flake8
```
Clone the repository, and run flake8:
```
git clone https://github.com/mozilla/mcom-tests.git
cd mcom-tests
flake8 . --ignore=E501
```
You will then see all of the issues found, below is an example:
```
./pages/desktop/base.py:48:17: E131 continuation line unaligned for hanging indent
./pages/desktop/base.py:48:27: E901 SyntaxError: invalid syntax
./pages/desktop/base.py:50:13: E123 closing bracket does not match indentation of opening bracket's line
./pages/desktop/base.py:53:13: E123 closing bracket does not match indentation of opening bracket's line
```
Fix all of the issues and rerun the last command until it reports no failures, and then submit a pull request with your fixes. If you need any assistance, either comment here or ask in #mozwebqa on irc.mozilla.org. Details of how to get onto IRC can be found [here](https://wiki.mozilla.org/IRC).

**Comment by rbillings** [comment]
Fix was merged, closing this issue.
