### ISSUE TITLE
Two tests are failing on mozilla.org test suites on dev, stage and prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/mcom-tests#408]
The failing tests are `test_major_link_urls_are_valid` in `test_about.py` [1] and `test_that_all_links_are_valid` in `test_notes.py` [2]. It looks like both may be issues with using `requests` to check for validity of links, as the failure messages indicate a `403` when checking the link.

Report of failures can be seen at https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.stage/165/HTML_Report/

@jgmize or @pmclanahan would either of you be willing to help investigate and fix this?

[1] https://github.com/mozilla/mcom-tests/blob/master/tests/test_about.py#L122
[2] https://github.com/mozilla/mcom-tests/blob/master/tests/test_notes.py#L23

**Comment by pmclanahan** [comment]
Taking it. Should have a PR soon.
