### ISSUE TITLE
Remove sign up test automation

### ISSUE THREAD

**Issue by rbillings** [mozilla/mcom-tests#419]
Bug 1164089 was filed as test automation is creating a lot of email data. We do not want to incur costs via sending emails, and have a plan set up to monitor new sign ups via unit tests and new relic in production- thus removing the need for these tests.

**Comment by stephendonner** [comment]
Thanks, Rebecca.  Closing this out as it was address/removed in https://github.com/mozilla/mcom-tests/pull/420
