### ISSUE TITLE
Remove test_tabzilla_links_are_visible tests/page objects

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#424]
Although we've worked hard to make the Tabzilla-visibility tests resilient, they still can be sporadic, and I in talking with a few #www folk, and looking through recent bugs, don't think they provide value vs. the benefit.

https://github.com/mozilla/mcom-tests/blob/master/tests/test_about.py#L66 and tests like it: 
tests.test_nightlyfirstrun.TestNightlyFirstRun 	test_tabzilla_links_are_visible
tests.test_mozillabased.TestMozillaBasedPagePage 	test_tabzilla_links_are_visible

I suggest we remove them.

**Comment by stephendonner** [comment]
I know @jgmize is a fan of this; @craigcook @alexgibson @kyoshino thoughts?

**Comment by alexgibson** [comment]
I believe @malena might even be working on [bug 1171928](https://bugzilla.mozilla.org/show_bug.cgi?id=1171928), so soon we can probably remove all tabzilla tests :+1:

**Comment by malena** [comment]
Yep I'm working on it. Thanks for tagging @alexgibson. Will remove those with the rest of the tabzilla stuff.

**Comment by davehunt** [comment]
I can't find any tabzilla references in the repo, so I'm guessing this has been done.

**Comment by davehunt** [comment]
Aha, it happened in https://github.com/mozilla/mcom-tests/commit/f65724e52c80754da9999c1dc2506e11ce83fdf5
