### ISSUE TITLE
test_sign_up_form_is_visible fails occasionally due to A/B test hiding the Contribute form

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#428]
We should figure out how best to (temporarily) address/avoid hitting A/B tests which do things like hide the Contribute form, specifically in this case, as in:

test_sign_up_form_is_visible

See https://webqa-ci.mozilla.com/job/mozilla.org.prod.win7.firefox.saucelabs/438/

@jgmize suggests passing in/appending this query string to the test: ?optimizely_opt_out=true

**Comment by stephendonner** [comment]
@davehunt thoughts?

**Comment by bobsilverberg** [comment]
Sounds reasonable to me, especially if this is something we might encounter in other tests.

@jgmize Is the recommendation that we add that to all of our urls? What happens if we visit a page via a url with that querystring and then click a link? Is the setting saved in a cookie or something, or would be then be faced with possible A/B problems because we navigated to a new page?

**Comment by jgmize** [comment]
my recommendation was to just add it to the test(s?) that are actually failing for now and verify that it actually corrects the problem.

**Comment by jgmize** [comment]
Yes, it saves the opt out in a cookie, and yes, there are likely going to be other issues caused by A/B tests, but I don't have enough information to make a long term risk mitigation strategy recommendation at this point.

**Comment by bobsilverberg** [comment]
@jgmize Fair enough, but I wonder, are there any downsides to just adding it globally at this point? Would we not want that option turned on for some tests?

**Comment by jgmize** [comment]
> @jgmize Fair enough, but I wonder, are there any downsides to just adding it globally at this point? Would we not want that option turned on for some tests?

My main concern is the notice that the optimizely js injects into the page to notify the user that they've been opted out of optimizely on the website, which may break the tests in other ways. I haven't audited their js (and even if I did they could change it tomorrow), nor have I actually seen this notice when testing the URL, but it describes it at the bottom of https://www.optimizely.com/opt_out/ and I'd rather just focus on trying to fix the known issue with this one test before we spend a bunch of time trying to come up with a global fix that could actually cause more issues.

**Comment by stephendonner** [comment]
Sadly, the commit didn't fix the issue, so reopening to remind us to revisit this.

**Comment by jgmize** [comment]
Reverted commit accidentally pushed to wrong branch that did not resolve issue.

**Comment by davehunt** [comment]
My first thought is that if Optimizely just writes a cookie, then we can forge that cookie ourselves when we first create our Selenium instance. I notice the cookie contents is not documented on their site though, so using the query string might be more future proof. A quick search found [this article](http://elementalselenium.com/tips/12-opt-out-of-ab-tests) which mentions both the cookie and query string approach.

Do we have some more information regarding why the commit did not fix the issue? Did we just commit and hope it would work, or was it tested successfully locally?

**Comment by jgmize** [comment]
> My first thought is that if Optimizely just writes a cookie, then we can forge that cookie ourselves when we first create our Selenium instance. I notice the cookie contents is not documented on their site though, so using the query string might be more future proof. A quick search found this article which mentions both the cookie and query string approach.

Yes, I thought about writing the cookie directly as well, but had similar concerns about future proofing, and as I mentioned in https://github.com/mozilla/mcom-tests/pull/429#issue-96474889 we're likely going to need to remove this particular test anyway, so it's not really worth messing with, IMO. Our long term approach doesn't involve using python for frontend tests anyway, so if/when we do need to solve the optimizely issue in the future then it will be using the approach outlined in http://bedrock.readthedocs.org/en/latest/testing.html

> Do we have some more information regarding why the commit did not fix the issue? Did we just commit and hope it would work, or was it tested successfully locally?

My original intent was to commit to a separate branch on my fork and test it from a separate jenkins instance I manage, but as I mentioned in https://github.com/mozilla/mcom-tests/issues/428#issuecomment-123558013 I made a mistake-- I fumbled a keystroke in https://github.com/magit/magit (normally I push my commits from the command line to avoid exactly that error on production repos, but I was in a hurry), which I have now reverted.
