### ISSUE TITLE
Consider bumping up timeout=3 value in test_urls.py, while we understand + address page-load times across apps

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mcom-tests#452]
We might want to bump up the "3" in the timeout=3 value, here: https://github.com/mozilla/mcom-tests/blob/master/tests/test_urls.py#L48

Unfortunately, although I'd love to see (and will continue to work to help drive down) page load times <3 seconds, the reality is that even without going through the dmz proxy in SCL3 that our test-automation does, we see >3 seconds page-load times on some of our applications:

https://rpm.newrelic.com/accounts/263620/browser

<img width="1671" alt="screen shot 2015-11-17 at 10 15 02 pm" src="https://cloud.githubusercontent.com/assets/387249/11234010/b1b6c8aa-8d78-11e5-890e-25d3dc29517e.png">

**Comment by davehunt** [comment]
Just to note that page load times are not the same as connect/response times. The tests in `test_urls` are not downloading all page resources. That said, I'm not against increasing this timeout. I'm not sure why it's set to 3 though, perhaps that is a success metric that we could either re-evaluate.

**Comment by stephendonner** [comment]
Good point, @davehunt and duly noted.  I will offer that even on my desktop's LAN-wired connection, in-office (MTV2), I've personally seen DNS resolution and TCP connects/transfers to GitHub/Fastly (CDN) and Google, etc. taking a /very/ long time (certainly something to chase up, long-term with NetOps), and this, I *think* is without having to go through the dmz proxy in SCL3 - to be sure, 10 seconds to load a page/resource/return a 200 OK via "requests" is too long.  However, the balance I'm attempting to strike, here, is the one between functional-test reliability and diluted/unrealistic-due-to-aggressive/unarticulated-firewall/DMZ expectations on our corporate LAN(s).  (Datacenters included!)

Can we, as a recourse:

1) increase the timeout to 10 seconds (I know, I know!)
2) somehow, assert the actual time it takes to resolve/connect/transfer/complete said request?

That might help us better-understand the problem(s) at hand, and escalate, as appropriate.

**Comment by davehunt** [comment]
> Can we, as a recourse:
1) increase the timeout to 10 seconds (I know, I know!)

I have no objection to this, we use 10 seconds elsewhere. It was obviously intentionally once set to 3 seconds, and I don't know the reasoning behind that, but I'm happy to increase it regardless.

> 2) somehow, assert the actual time it takes to resolve/connect/transfer/complete said request?

I'm not sure I understand this one. If it takes longer than the timeout we'll get a failure, isn't that enough? Independently, it may make sense to bring up some performance tests like WebPageTest. Perhaps that's what you're referring to here?

Additionally, I'd like to ask how useful these particular tests are. They basically check that ~30 URLs have no more than 1 redirect and return an ok response code. If there's value in them, great, but if not let's remove them. I suspect some are duplicated in the redirect tests, some are duplicated by the functional tests, and some would be made redundant by a thorough link checker.

**Comment by davehunt** [comment]
The tests have been migrated to the https://github.com/mozilla/bedrock repository. If this is still needed, it should be opened there.
